export const ASIT_SCHEDULE_TEXT = {
    ru: {
      title: "График АСИТ",
      subtitle: "Схема лечения",
      description:
        "Укажите схему аллерген-специфической иммунотерапии, интервал между дозами, дату последней выполненной дозы и ближайшее запланированное событие.",
      regimen: "Схема лечения",
      conventional: "Конвенциональная",
      daily: "Ежедневный приём",
      accelerated: "Ускоренная",
      startDate: "Дата начала терапии",
      lastDoseDate: "Дата последней дозы / инъекции",
      lastDoseDateHint:
        "От этой даты рассчитывается следующая инъекция. Если это первая доза, можно оставить пустым — тогда расчёт будет от даты начала терапии.",
      intervalDays: "Интервал между дозами, дней",
      doseUnit: "Единица дозы",
      doseUnitPlaceholder: "Например: мл / капли / таблетка / инъекция",
      nextEventDate: "Дата следующей дозы / инъекции",
      calculateNextDate: "Рассчитать следующую дату",
      doseValue: "Доза следующего события",
      doseValuePlaceholder: "Например: 0.5 мл / 5 капель / 1 таблетка",
      save: "Сохранить схему",
      saving: "Сохраняем...",
      saved: "Схема АСИТ сохранена",
      loading: "Загружаем схему...",
      loadError: "Не удалось загрузить схему АСИТ",
      saveError: "Не удалось сохранить схему АСИТ",
      reminderTitle: "Оповещение",
      noReminder: "Ближайшая инъекция пока не требует напоминания.",
      todayReminder:
        "Сегодня запланирована очередная доза АСИТ. Следуйте схеме лечения и рекомендациям врача.",
      overdueReminder:
        "Дата очередной дозы уже прошла. Свяжитесь с врачом для уточнения дальнейшей схемы.",
      weekReminder:
        "Через неделю должна быть очередная инъекция — запланируйте визит к врачу.",
      daysLeft: "Осталось дней",
      currentPlan: "Текущая схема",
      selectedRegimen: "Выбранная схема",
      nextEvent: "Ближайшее событие",
      recentEvents: "События АСИТ",
      noEvents: "События ещё не запланированы.",
      doctorWarning:
        "АСИТ проводится только по назначению и под контролем врача-аллерголога. Не изменяйте дозу и интервал самостоятельно.",
      planned: "Запланировано",
      done: "Выполнено",
      skipped: "Пропущено",
      rescheduled: "Перенесено",
      markDone: "Отметить как выполнено",
      markingDone: "Отмечаем...",
      markedDone: "Событие отмечено как выполненное",
      actualDate: "Фактическая дата",
    },
  
    en: {
      title: "ASIT schedule",
      subtitle: "Treatment plan",
      description:
        "Enter the allergen-specific immunotherapy regimen, interval between doses, last completed dose date, and the next planned event.",
      regimen: "Treatment regimen",
      conventional: "Conventional",
      daily: "Daily intake",
      accelerated: "Accelerated",
      startDate: "Therapy start date",
      lastDoseDate: "Last dose / injection date",
      lastDoseDateHint:
        "The next injection is calculated from this date. If this is the first dose, leave it empty and the start date will be used.",
      intervalDays: "Interval between doses, days",
      doseUnit: "Dose unit",
      doseUnitPlaceholder: "For example: ml / drops / tablet / injection",
      nextEventDate: "Next dose / injection date",
      calculateNextDate: "Calculate next date",
      doseValue: "Next event dose",
      doseValuePlaceholder: "For example: 0.5 ml / 5 drops / 1 tablet",
      save: "Save plan",
      saving: "Saving...",
      saved: "ASIT plan saved",
      loading: "Loading ASIT plan...",
      loadError: "Failed to load ASIT plan",
      saveError: "Failed to save ASIT plan",
      reminderTitle: "Reminder",
      noReminder: "The next injection does not require a reminder yet.",
      todayReminder:
        "The next ASIT dose is scheduled for today. Follow your treatment plan and doctor’s recommendations.",
      overdueReminder:
        "The planned dose date has already passed. Contact your doctor to clarify the next steps.",
      weekReminder:
        "The next injection is due within a week — schedule a doctor visit.",
      daysLeft: "Days left",
      currentPlan: "Current plan",
      selectedRegimen: "Selected regimen",
      nextEvent: "Next event",
      recentEvents: "ASIT events",
      noEvents: "No events have been scheduled yet.",
      doctorWarning:
        "ASIT is carried out only as prescribed and supervised by an allergist. Do not change the dose or interval by yourself.",
      planned: "Planned",
      done: "Done",
      skipped: "Skipped",
      rescheduled: "Rescheduled",
      markDone: "Mark as done",
      markingDone: "Marking...",
      markedDone: "Event marked as done",
      actualDate: "Actual date",
    },
  
    kk: {
      title: "АСИТ кестесі",
      subtitle: "Емдеу схемасы",
      description:
        "Аллерген-спецификалық иммунотерапия схемасын, дозалар арасындағы интервалды, соңғы орындалған доза күнін және келесі жоспарланған оқиғаны көрсетіңіз.",
      regimen: "Емдеу схемасы",
      conventional: "Конвенционалды",
      daily: "Күнделікті қабылдау",
      accelerated: "Жеделдетілген",
      startDate: "Терапияның басталу күні",
      lastDoseDate: "Соңғы доза / инъекция күні",
      lastDoseDateHint:
        "Келесі инъекция осы күннен есептеледі. Егер бұл бірінші доза болса, бос қалдыруға болады — онда терапияның басталу күні қолданылады.",
      intervalDays: "Дозалар арасындағы интервал, күн",
      doseUnit: "Доза бірлігі",
      doseUnitPlaceholder: "Мысалы: мл / тамшы / таблетка / инъекция",
      nextEventDate: "Келесі доза / инъекция күні",
      calculateNextDate: "Келесі күнді есептеу",
      doseValue: "Келесі оқиғаның дозасы",
      doseValuePlaceholder: "Мысалы: 0.5 мл / 5 тамшы / 1 таблетка",
      save: "Схеманы сақтау",
      saving: "Сақталуда...",
      saved: "АСИТ схемасы сақталды",
      loading: "АСИТ схемасы жүктелуде...",
      loadError: "АСИТ схемасын жүктеу мүмкін болмады",
      saveError: "АСИТ схемасын сақтау мүмкін болмады",
      reminderTitle: "Еске салу",
      noReminder: "Келесі инъекция әзірге еске салуды қажет етпейді.",
      todayReminder:
        "Бүгін АСИТ дозасы жоспарланған. Емдеу схемасын және дәрігер ұсынымдарын сақтаңыз.",
      overdueReminder:
        "Жоспарланған доза күні өтіп кеткен. Әрі қарайғы схеманы нақтылау үшін дәрігерге хабарласыңыз.",
      weekReminder:
        "Бір апта ішінде кезекті инъекция болуы керек — дәрігерге баруды жоспарлаңыз.",
      daysLeft: "Қалған күн",
      currentPlan: "Ағымдағы схема",
      selectedRegimen: "Таңдалған схема",
      nextEvent: "Келесі оқиға",
      recentEvents: "АСИТ оқиғалары",
      noEvents: "Оқиғалар әлі жоспарланбаған.",
      doctorWarning:
        "АСИТ тек дәрігер-аллергологтың тағайындауы және бақылауымен жүргізіледі. Дозаны және интервалды өз бетіңізше өзгертпеңіз.",
      planned: "Жоспарланған",
      done: "Орындалды",
      skipped: "Өткізілді",
      rescheduled: "Ауыстырылды",
      markDone: "Орындалды деп белгілеу",
      markingDone: "Белгіленуде...",
      markedDone: "Оқиға орындалды деп белгіленді",
      actualDate: "Нақты күні",
    },
  };
  
  export const ASIT_REGIMENS = [
    {
      value: "conventional",
      labelKey: "conventional",
      description: {
        ru: "Постепенное увеличение дозы по стандартной схеме.",
        en: "Gradual dose increase according to a standard schedule.",
        kk: "Стандартты схема бойынша дозаны біртіндеп арттыру.",
      },
    },
    {
      value: "daily",
      labelKey: "daily",
      description: {
        ru: "Ежедневный приём препарата, чаще подходит для сублингвальных форм.",
        en: "Daily medication intake, often used for sublingual forms.",
        kk: "Күнделікті қабылдау, көбіне тіл астына қолданылатын формаларға сәйкес келеді.",
      },
    },
    {
      value: "accelerated",
      labelKey: "accelerated",
      description: {
        ru: "Ускоренный набор дозы под более строгим медицинским контролем.",
        en: "Accelerated dose build-up under closer medical supervision.",
        kk: "Дозаны жедел арттыру, қатаң медициналық бақылаумен жүргізіледі.",
      },
    },
  ];